# **Numpy**

In [2]:
import numpy as np
print ("imported")

imported


In [3]:
ls = [1,2,3,4,5]
ls

[1, 2, 3, 4, 5]

In [4]:
ls = [1,2,3,4,5]
arr = np.array(ls)
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr+5

array([ 6,  7,  8,  9, 10])

In [7]:
arr.ndim

1

In [8]:
arr.shape

(5,)

In [9]:
arr.size

5

In [10]:
arr.dtype

dtype('int64')

In [12]:
ls = [6,7,8,9,10]
arr2 = np.array(ls)

In [19]:
ls = [1, 2, 3, 4, 5]
for i in ls:
    if i<5:
        print (i)

arr[arr<5]

1
2
3
4


array([1, 2, 3, 4])