# Numpy

In [1]:
import numpy as np
print ("imported")

imported


In [2]:
ls = [1,2,3,4,5]
ls

[1, 2, 3, 4, 5]

In [3]:
ls = [1,2,3,4,5]
arr = np.array(ls)
arr

array([1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr+5

array([ 6,  7,  8,  9, 10])

In [9]:
arr.ndim

1

In [10]:
arr.shape

(5,)

In [11]:
arr.size

5

In [12]:
arr.dtype

dtype('int64')

In [13]:
ls = [6,7,8,9,10]
arr2 = np.array(ls)

In [14]:
ls = [1, 2, 3, 4, 5]
for i in ls:
    if i<5:
        print (i)

arr[arr<5]

1
2
3
4


array([1, 2, 3, 4])