# **Numpy**

In [1]:
import numpy as np
print ("imported")

imported


In [2]:
ls = [1,2,3,4,5]
ls

[1, 2, 3, 4, 5]

In [3]:
ls = [1,2,3,4,5]
arr = np.array(ls)
arr

array([1, 2, 3, 4, 5])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr+5

array([ 6,  7,  8,  9, 10])

In [6]:
arr.ndim

1

In [7]:
arr.shape

(5,)

In [8]:
arr.size

5

In [9]:
arr.dtype

dtype('int64')

In [62]:
ls = [6,7,8,9,10]
arr2 = np.array(ls)

In [64]:
ls = [1, 2, 3, 4, 5]
for i in ls:
    if i<6:
        print (i)

arr[arr<5]

1
2
3
4
5


array([1, 2, 3, 4])

In [78]:
# array creations 
arr3 = np.arange(100)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [83]:
arr10=np.ones((2,5))
# gives 2d arrray of ones
arr10

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [81]:
arr10.flatten()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [67]:
np.zeros((2,5))
# gives 2d array of zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.arange(0,10,2)
# hear the 0 is the start| 10 is the last element| and 2 is the step.

array([0, 2, 4, 6, 8])

In [16]:
np.linspace(0,10,3)
# array of evenly spaced numbers from 0 -10 gives any 3 values

array([ 0.,  5., 10.])

In [74]:
import random
random.random()

0.8351583282468595

In [17]:
np.linspace(0,10)
# this will take default n value as 50 that is why it is giving me this result

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [18]:
np.eye(4)
# it gives identity matrix of 4 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
import random
random.randint(0,10)
random.random()

0.6754511898109558

In [20]:
ls2 = ["abi","khushi","ram"]
random.choice(ls2)

'khushi'

In [21]:
random.choices(ls2, k=2)

['abi', 'ram']

In [22]:
random.shuffle(ls2)
ls2

['abi', 'ram', 'khushi']

In [23]:
random.randint(1,50)

10

In [24]:
[random.randint(1,50) for _ in range(10)]
# this will give you random 10 elements from 1-50, 10 elements

[1, 40, 27, 5, 16, 7, 8, 37, 41, 15]

In [25]:
# ---------------------------
arr4 = np.arange(60)
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [26]:
# now we will reshape to 2d array of 60 elements 
arr4.reshape(12,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [27]:
arr4.reshape(10,3,2)
# this gives reshape to 3d array if 60 elements

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35]],

       [[36, 37],
        [38, 39],
        [40, 41]],

       [[42, 43],
        [44, 45],
        [46, 47]],

       [[48, 49],
        [50, 51],
        [52, 53]],

       [[54, 55],
        [56, 57],
        [58, 59]]])

In [28]:
arr5 = np.resize(arr,(25,25))
arr5
# arr5 will be a 25×25 array filled by repeating elements of arr

array([[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2,
        3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2,
        3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2,
        3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2,
        3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2,
        3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2,
        3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2,
        3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2,
        3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2,
        3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2,
        3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2,
      

In [29]:
# It converts the 2D array (25 × 25) into a 1D array with 625 elements.
arr5.reshape(625)

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2,
       3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4,
       5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1,
       2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3,
       4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5,
       1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2,
       3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4,
       5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1,
       2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3,
       4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5,
       1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2,
       3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4,
       5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1,
       2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1,

In [30]:
# ------------------
# now funtions
# It generates a NumPy array of 100 random integers between 1 and 9 (NOT 10) - alternative way of loops that i made above.
arr7 = np.random.randint(1,10,100)
arr7

array([8, 7, 4, 7, 2, 2, 1, 7, 7, 7, 6, 4, 6, 3, 8, 6, 6, 9, 8, 9, 3, 4,
       8, 9, 9, 4, 6, 1, 3, 9, 8, 2, 3, 2, 7, 9, 8, 1, 7, 1, 7, 4, 9, 9,
       1, 2, 3, 8, 6, 6, 1, 8, 9, 5, 7, 1, 3, 8, 1, 6, 6, 1, 4, 7, 1, 5,
       9, 3, 2, 2, 5, 5, 7, 9, 1, 1, 5, 1, 1, 3, 9, 3, 3, 6, 8, 5, 5, 2,
       9, 5, 5, 1, 6, 5, 9, 9, 1, 7, 8, 1], dtype=int32)

In [31]:
arr7.min()

np.int32(1)

In [32]:
arr7.max()

np.int32(9)

In [33]:
arr7.mean()

np.float64(5.1)

In [34]:
arr7.sum()

np.int64(510)

In [35]:
# let us transpose the value 
arr8 = np.random.randint(1,50,(4,2))
arr8

array([[ 9,  5],
       [45, 14],
       [17,  7],
       [45, 29]], dtype=int32)

In [36]:
arr8.T

array([[ 9, 45, 17, 45],
       [ 5, 14,  7, 29]], dtype=int32)

In [37]:
# -------------
# indexing
arr9 = np.random.randint(2,12,(10,5))
arr9

array([[ 7, 10,  4,  2,  3],
       [ 9,  7,  2,  5,  6],
       [10,  2,  3,  6,  2],
       [ 9,  5,  6,  6, 10],
       [ 4, 11,  3,  3,  8],
       [ 7, 10,  9,  9,  7],
       [10,  2,  7,  5,  7],
       [ 9,  3,  5,  5, 10],
       [ 5, 10,  4,  6, 10],
       [11,  8,  8, 11, 10]], dtype=int32)

In [38]:
# if i need the values from 7 index to last end.
# arr9[7:] or
arr9[7:10]

array([[ 9,  3,  5,  5, 10],
       [ 5, 10,  4,  6, 10],
       [11,  8,  8, 11, 10]], dtype=int32)

In [39]:
arr9[1:5]

array([[ 9,  7,  2,  5,  6],
       [10,  2,  3,  6,  2],
       [ 9,  5,  6,  6, 10],
       [ 4, 11,  3,  3,  8]], dtype=int32)

In [40]:
arr9[0:10,0:2]

array([[ 7, 10],
       [ 9,  7],
       [10,  2],
       [ 9,  5],
       [ 4, 11],
       [ 7, 10],
       [10,  2],
       [ 9,  3],
       [ 5, 10],
       [11,  8]], dtype=int32)

In [41]:
arr9[0:5,0:4]

array([[ 7, 10,  4,  2],
       [ 9,  7,  2,  5],
       [10,  2,  3,  6],
       [ 9,  5,  6,  6],
       [ 4, 11,  3,  3]], dtype=int32)

In [42]:
# making of 3d array, here 2-10 are the elements..|5 is the block, 10 is the row and 5 is the col|- is called shape
arr10 = np.random.randint(2,10,(5,10,5))
arr10

array([[[9, 2, 4, 2, 8],
        [9, 3, 8, 6, 5],
        [2, 5, 4, 3, 9],
        [9, 6, 7, 2, 7],
        [4, 6, 6, 5, 9],
        [4, 8, 3, 9, 8],
        [3, 3, 6, 7, 9],
        [4, 4, 2, 5, 3],
        [2, 6, 4, 6, 8],
        [4, 9, 9, 4, 8]],

       [[3, 3, 9, 3, 9],
        [7, 2, 5, 9, 9],
        [9, 4, 8, 3, 3],
        [3, 4, 8, 9, 2],
        [9, 6, 9, 3, 8],
        [6, 4, 7, 4, 4],
        [7, 8, 5, 2, 7],
        [4, 7, 7, 9, 3],
        [6, 2, 7, 5, 8],
        [9, 6, 9, 6, 6]],

       [[5, 7, 5, 4, 3],
        [7, 4, 4, 8, 8],
        [9, 8, 7, 2, 2],
        [3, 5, 4, 8, 7],
        [9, 9, 8, 6, 4],
        [8, 2, 5, 7, 7],
        [8, 4, 4, 5, 5],
        [2, 8, 3, 6, 7],
        [3, 9, 9, 4, 4],
        [4, 6, 8, 7, 3]],

       [[7, 8, 6, 9, 4],
        [4, 5, 4, 3, 2],
        [9, 6, 2, 3, 4],
        [8, 8, 7, 5, 7],
        [2, 3, 4, 8, 5],
        [9, 3, 7, 8, 2],
        [3, 9, 3, 2, 7],
        [4, 8, 4, 8, 3],
        [4, 4, 6, 9, 4],
        [3, 5, 5, 2

In [43]:
arr10.ndim

3

In [44]:
arr10.shape

(5, 10, 5)

In [45]:
# INDEXING
arr10[0]

array([[9, 2, 4, 2, 8],
       [9, 3, 8, 6, 5],
       [2, 5, 4, 3, 9],
       [9, 6, 7, 2, 7],
       [4, 6, 6, 5, 9],
       [4, 8, 3, 9, 8],
       [3, 3, 6, 7, 9],
       [4, 4, 2, 5, 3],
       [2, 6, 4, 6, 8],
       [4, 9, 9, 4, 8]], dtype=int32)

In [46]:
# this will reverse
arr10[::-1]

array([[[6, 9, 8, 8, 9],
        [3, 4, 7, 5, 2],
        [6, 7, 4, 3, 4],
        [3, 4, 8, 5, 2],
        [9, 9, 8, 7, 4],
        [2, 3, 6, 8, 4],
        [6, 6, 7, 5, 6],
        [6, 7, 4, 4, 5],
        [7, 8, 4, 8, 6],
        [5, 3, 5, 3, 6]],

       [[7, 8, 6, 9, 4],
        [4, 5, 4, 3, 2],
        [9, 6, 2, 3, 4],
        [8, 8, 7, 5, 7],
        [2, 3, 4, 8, 5],
        [9, 3, 7, 8, 2],
        [3, 9, 3, 2, 7],
        [4, 8, 4, 8, 3],
        [4, 4, 6, 9, 4],
        [3, 5, 5, 2, 2]],

       [[5, 7, 5, 4, 3],
        [7, 4, 4, 8, 8],
        [9, 8, 7, 2, 2],
        [3, 5, 4, 8, 7],
        [9, 9, 8, 6, 4],
        [8, 2, 5, 7, 7],
        [8, 4, 4, 5, 5],
        [2, 8, 3, 6, 7],
        [3, 9, 9, 4, 4],
        [4, 6, 8, 7, 3]],

       [[3, 3, 9, 3, 9],
        [7, 2, 5, 9, 9],
        [9, 4, 8, 3, 3],
        [3, 4, 8, 9, 2],
        [9, 6, 9, 3, 8],
        [6, 4, 7, 4, 4],
        [7, 8, 5, 2, 7],
        [4, 7, 7, 9, 3],
        [6, 2, 7, 5, 8],
        [9, 6, 9, 6

In [47]:
arr11 = np.random.randint([7,5,9])
arr11
# generates an array of random integer from 0 to the corresponding value (exclusive) in the list.

array([1, 0, 0], dtype=int32)

In [48]:
arr11.argmax()

np.int64(0)

In [49]:
arr11.argmin()

np.int64(1)

In [50]:
arr11.sort()
arr11
# this will reorder the elements

array([0, 0, 1], dtype=int32)

In [51]:
arr11[::-1]
# reverse the elements

array([1, 0, 0], dtype=int32)

In [52]:
np.unique(arr)

array([1, 2, 3, 4, 5])

In [53]:
np.median(arr)

np.float64(3.0)

In [54]:
np.sqrt(25)

np.float64(5.0)

In [55]:
arr11.var()
# Returns the variance of the array

np.float64(0.22222222222222224)

In [56]:
arr11.std
# Returns the standard deviation of the array

<function ndarray.std>