# NumPy

# xyz for h1 - docs.scipy.org offl site 
*abishek* - italic
**abishek** - Bold 
***abishek*** - Bold and italic

In [1]:
import numpy as np

In [2]:
print("Hello World")

Hello World


In [3]:
# making an numpy array 
myarr = np.array([1,2,3,4,5])

In [4]:
myarr

array([1, 2, 3, 4, 5])

In [5]:
# making an arr and dtype 
# the greater number you select the bit you have to raise like 8,16,32,64...
# this is called memory management 
myarr = np.array([1,16,4,55], np.int8)

In [6]:
myarr

array([ 1, 16,  4, 55], dtype=int8)

In [7]:
# to get/fetch the element by index
myarr[3]

np.int8(55)

In [8]:
# how to make 2D arr
arr = np.array([[22,24,25,27]])
arr[0,1] # 0 is row and 1 is col its 24


np.int64(24)

In [9]:
# to know the dimention of the arr
myarr.shape # it has 4 row and 0 col

(4,)

In [10]:
arr.shape # it has 1 row and 4 col

(1, 4)

In [11]:
arr.dtype # this tell the data type and memory it is using and default it use 64 unless u change it.

dtype('int64')

In [12]:
# if i want to change the element in that specific index
arr[0,1] =69 # this is was 24 to change this 

In [13]:
arr # 24 changed to 69

array([[22, 69, 25, 27]])

# Array creation : Convertion from the other python structure

In [14]:
listarr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [15]:
listarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
listarr.dtype 

dtype('int64')

In [17]:
listarr.shape 

(3, 3)

In [18]:
listarr.size 
# size tells the total number of elements 

9

In [19]:
# We make array for only for integer and float not objects 

In [20]:
# -----------------------------------

In [21]:
zeros = np.zeros((2,5))
# create numpy array with zeros, default takes as float.

In [22]:
zeros 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
# --------------------------------
range = np.arange(15)
range 
# this gives the numpy array of 0 to (n-1) array 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
# -----------------------
lspace = np.linspace(1,10,5)
lspace 
# In this 1- first element, 10 - last element, 5 - is the total content present.

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [25]:
empty = np.empty((2,5))
empty 
# it does not always fill with 0s, just allocates memory with garbage value.
# used when you want to fill the array with actual data.

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
emp = np.empty_like(lspace)
emp
# this is more efficient and less space consuming

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [27]:
# -------------------
identity_matrix = np.identity(5)
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
a = np.array([1,2,3,4,5,6])
# a = np.arange(7)
# the above both are same way to represent


# at the end both tells the dimentions only
a.shape # tell the length 5
a.ndim # tell the Number of dimensions: 1D

1

In [29]:
# if i want suppose want to convert the 1D into 2 by 3 of a NOTE; it will be coverted in 2 by3 only since it has 6 elements
y= a.reshape((2,3)) #2x3 = 6, 3x2 =6 
y

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
# as you can see the digits are arranged rows wise, what if i want to arrange it in col wise then
x= a.reshape((2,3),order = "F")
x

array([[1, 3, 5],
       [2, 4, 6]])

In [31]:
# --------------------------
# using of ravel to make it as it was befor into !D
x.ravel()


array([1, 3, 5, 2, 4, 6])

In [39]:
# ------------------
# NumPy Axis
z = [[1,2,3],[4,5,6],[7,1,0]]
array = np.array(z)
array 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [40]:
array.sum(axis=0)
# this gives the sum of the y axis elements

array([12,  8,  9])

In [43]:
array.sum(axis=1)
# this is gives the sum of the x axis elements

array([ 6, 15,  8])

In [44]:
# Methods and attributes 
array.T
# this is gives the transpose of the 'array'

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [45]:
for item in array.flat:
    print(item)
# this is will give the 1D iterator of all the array elements 

1
2
3
4
5
6
7
1
0


In [48]:
array.ndim
since we made this 2D array.

2

In [50]:
# to find the number of the elements of the array 
array.size

9

In [51]:
array.nbytes 
this tells the number of bytes that is consumed by the array to store the value 

72

In [54]:
# -----------------------------
# methods
one = np.array([1,44,444,88,96])
one

array([  1,  44, 444,  88,  96])

In [55]:
one.argmax()
tells the index of the max number present

np.int64(2)

In [56]:
one.argmin()

np.int64(0)

In [64]:
one.argsort()
# this tells the indexs of the sort array should be.

array([0, 1, 3, 4, 2])

In [65]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [66]:
array.argmin()
# the 8th index having the min number

np.int64(8)

In [67]:
array.argmax()
# the 6th index having the max value

np.int64(6)

In [68]:
array.argmax(axis=0)
gives the index of the max value in y axis 

array([2, 1, 1])

In [70]:
array.argmax(axis=1)
# gives the index of the max value in x axis 

array([2, 2, 0])

In [71]:
array.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [73]:
array.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [84]:
array.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [85]:
# ---------------------
martrix addtion, multiplication
array 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [87]:
array2 = np.array([[1, 5, 3],
       [4, 1, 6],
       [7, 5, 0]])
array2

array([[1, 5, 3],
       [4, 1, 6],
       [7, 5, 0]])

In [88]:
array + array2

array([[ 2,  7,  6],
       [ 8,  6, 12],
       [14,  6,  0]])

In [89]:
array * array2

array([[ 1, 10,  9],
       [16,  5, 36],
       [49,  5,  0]])

In [92]:
np.sqrt(array)
# does the sq of the each element

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [94]:
array.max()

np.int64(7)

In [95]:
array.min()

np.int64(0)

In [97]:
array.sum()

np.int64(29)

In [98]:
# ------------------------
# how to find my element
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [104]:
np.where(array>5)
# type(np.where(array>5)) # gives the tuple 
# plot this you will get the ans - index of 1st row and 2nd col is the largest number 

tuple

In [101]:
np.count_nonzero(array)
# there is one zero, so 8 elements

8

In [107]:
# -----------------
import sys
py_arr = [1,2,3,4]
py_arr

[1, 2, 3, 4]

In [112]:
np_arr = np.array(py_arr)
np_arr

array([1, 2, 3, 4])

In [116]:
sys.getsizeof(1) * len(py_arr)

112

In [117]:
np_arr.itemsize * np_arr.size

32

# intro end 