# Numpy


In [6]:
import numpy as np
print("imported")

imported 


In [7]:
ls = [1,2,3,4,5,6]
ls

[1, 2, 3, 4, 5, 6]

In [9]:
ls = [1,2,3,4,5,6]
arr = np.array(ls)
ls

[1, 2, 3, 4, 5, 6]

In [10]:
type(arr)

numpy.ndarray

In [11]:
arr+5

array([ 6,  7,  8,  9, 10, 11])

In [12]:
arr.dtype

dtype('int32')

In [13]:
arr.ndim

1

In [16]:
ls = [1,2,3,4,5,6]
arr2 = np.array(ls)
arr2[2]

3

In [17]:
ls = [1,2,3,4,5,6]
arr2 = np.array(ls)
arr2[2:5:2]

array([3, 5])

In [22]:
ls = [1,2,3,4,5,6]
# for i in ls:
#     if i < 5:
#         print(i)
arr[arr<5]

array([1, 2, 3, 4])

In [23]:
arr.size

6

In [24]:
len(arr)

6

In [26]:
arr2 = np.arange(100)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [27]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [33]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
np.linspace(1,8,5)

array([1.  , 2.75, 4.5 , 6.25, 8.  ])

In [37]:
import random 

In [39]:
random.randint(1,10)

1

In [40]:
random.random()

0.11164272584567969

In [42]:
ls = ["abi","chetan","aman"]
random.choice(ls)

'chetan'

In [44]:
random.choices(ls,k=2)

['chetan', 'aman']