# Numpy


In [1]:
import numpy as np
print("imported")

imported


In [2]:
ls = [1,2,3,4,5,6]
ls

[1, 2, 3, 4, 5, 6]

In [3]:
ls = [1,2,3,4,5,6]
arr = np.array(ls)
ls

[1, 2, 3, 4, 5, 6]

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr+5

array([ 6,  7,  8,  9, 10, 11])

In [6]:
arr.dtype

dtype('int32')

In [7]:
arr.ndim

1

In [8]:
ls = [1,2,3,4,5,6]
arr2 = np.array(ls)
arr2[2]

3

In [9]:
ls = [1,2,3,4,5,6]
arr2 = np.array(ls)
arr2[2:5:2]

array([3, 5])

In [10]:
ls = [1,2,3,4,5,6]
# for i in ls:
#     if i < 5:
#         print(i)
arr[arr<5]

array([1, 2, 3, 4])

In [11]:
arr.size

6

In [12]:
len(arr)

6

In [13]:
arr2 = np.arange(100)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.linspace(1,8,5)

array([1.  , 2.75, 4.5 , 6.25, 8.  ])

In [18]:
import random 

In [19]:
random.randint(1,10)

9

In [20]:
random.random()

0.8072561791011856

In [21]:
ls = ["abi","chetan","aman"]
random.choice(ls)

'aman'

In [22]:
random.choices(ls,k=2)

['aman', 'chetan']

In [23]:
random.shuffle(ls)
ls

['chetan', 'abi', 'aman']

In [24]:
np.random.randint(1,50,10)

array([25,  8, 29, 46, 27, 32, 49,  3, 45, 35])

In [25]:
!python --version

Python 3.8.10


In [26]:
np.random.randint(1,50,(10,5))

array([[18, 25, 37, 14, 42],
       [24, 37, 23,  6, 24],
       [49, 44, 34, 14, 18],
       [43,  9, 49, 47, 40],
       [ 6, 10, 11, 39, 40],
       [30, 24,  5, 24, 22],
       [41, 37, 43, 43, 11],
       [37,  2, 18, 16, 27],
       [23, 32, 41,  8, 40],
       [34, 10, 25, 22, 41]])

In [27]:
arr = np.arange(60)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [28]:
arr.reshape(12,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [29]:
arr.reshape(10,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35]],

       [[36, 37],
        [38, 39],
        [40, 41]],

       [[42, 43],
        [44, 45],
        [46, 47]],

       [[48, 49],
        [50, 51],
        [52, 53]],

       [[54, 55],
        [56, 57],
        [58, 59]]])

In [30]:
arr2 = np.resize(arr,(25,25))
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,
         6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
        31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
        11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 

In [31]:
arr.shape

(60,)

In [32]:
arr2.reshape(625)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,
         6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
        31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
        11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 

In [33]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [34]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [35]:
arr2 = np.random.randint(5,50,100)
arr2

array([48, 27, 16, 24, 27, 48, 46, 45, 25, 29,  8, 13, 36, 33, 28, 32, 44,
       31, 19, 34, 21, 46, 13, 12, 31, 47, 41,  8, 37, 31, 35, 18, 18, 33,
       39,  9, 10, 46, 41, 22, 15, 38, 32, 41, 36, 24, 16, 25,  9, 13, 31,
       37, 36, 16, 20, 19, 44, 49, 20, 26, 45,  9, 36, 10, 25, 39, 48, 13,
       48, 26, 17,  5, 28, 45, 45, 11, 49, 41, 28, 12, 15, 25, 49, 17, 42,
       33, 49, 21, 13, 48, 12, 48, 24, 28, 10,  7, 12, 49, 42, 41])

In [36]:
arr.min()

0

In [37]:
arr.max()

59

In [38]:
arr.mean()

29.5

In [39]:
arr.sum()

1770

In [40]:
arr2 = np.random.randint(5,50,(4,3))
arr2

array([[47, 16, 21],
       [31, 26, 35],
       [13, 27, 37],
       [47, 20, 19]])

In [41]:
arr2.T

array([[47, 31, 13, 47],
       [16, 26, 27, 20],
       [21, 35, 37, 19]])

In [42]:
arr = np.random.randint(2,12,(10,5))
arr

array([[10,  4,  3,  8,  5],
       [ 6,  9,  6, 10,  7],
       [ 9,  2,  7,  5,  4],
       [ 4,  8,  6,  7,  9],
       [ 7,  5,  9,  5, 11],
       [ 4, 11,  3,  7,  2],
       [ 3,  3, 11,  7,  5],
       [11,  2,  2, 11,  5],
       [11,  9,  7, 10,  5],
       [ 7,  7,  7,  9,  6]])

In [43]:
arr[7:]

array([[11,  2,  2, 11,  5],
       [11,  9,  7, 10,  5],
       [ 7,  7,  7,  9,  6]])

In [44]:
arr[2:5]

array([[ 9,  2,  7,  5,  4],
       [ 4,  8,  6,  7,  9],
       [ 7,  5,  9,  5, 11]])

In [45]:
arr[0:10,0:2]

array([[10,  4],
       [ 6,  9],
       [ 9,  2],
       [ 4,  8],
       [ 7,  5],
       [ 4, 11],
       [ 3,  3],
       [11,  2],
       [11,  9],
       [ 7,  7]])

In [46]:
arr[:,:2]

array([[10,  4],
       [ 6,  9],
       [ 9,  2],
       [ 4,  8],
       [ 7,  5],
       [ 4, 11],
       [ 3,  3],
       [11,  2],
       [11,  9],
       [ 7,  7]])

In [47]:
arr[3:6,2:]

array([[ 6,  7,  9],
       [ 9,  5, 11],
       [ 3,  7,  2]])

In [48]:
arr[0::2,2:]

array([[ 3,  8,  5],
       [ 7,  5,  4],
       [ 9,  5, 11],
       [11,  7,  5],
       [ 7, 10,  5]])

In [49]:
arr2 =np.random.randint(2,50,(5,10,5))
arr2

array([[[39, 20, 41, 43,  4],
        [18, 48,  2, 21, 31],
        [31, 11, 20, 46, 27],
        [27, 37, 45, 20, 38],
        [42, 10,  4, 25, 18],
        [18, 21, 27,  5, 47],
        [31, 42,  3, 28, 26],
        [16, 23, 34, 10, 19],
        [10, 27, 30, 25, 27],
        [49,  2,  7, 29, 26]],

       [[37, 16,  8, 43, 33],
        [35, 21, 44, 49, 19],
        [32,  5, 27, 26, 41],
        [ 2, 43, 46,  6, 22],
        [47, 35, 35, 25, 36],
        [ 7, 40, 24, 31, 36],
        [43, 29, 34, 44, 33],
        [39, 45, 24, 28, 29],
        [28, 42, 17, 45, 31],
        [16, 48, 34, 37,  6]],

       [[46, 44,  6, 12,  7],
        [44, 37, 48, 34, 45],
        [ 5,  5, 16, 43, 41],
        [27, 17, 13, 23, 23],
        [ 7, 20, 42, 28, 36],
        [41, 25, 26, 42, 35],
        [21, 31, 37, 14, 33],
        [49, 38, 33, 25, 11],
        [20, 36, 46,  4, 43],
        [16, 24, 27, 15, 24]],

       [[38, 48, 12, 21,  5],
        [37, 18, 38, 42, 39],
        [ 8, 43,  8, 10,  5],
    

In [50]:
arr.shape

(10, 5)

In [51]:
arr.ndim

2

In [52]:
arr[0]

array([10,  4,  3,  8,  5])

In [53]:
arr2= arr[0]
arr2

In [59]:
arr2

array([[[39, 20, 41, 43,  4],
        [18, 48,  2, 21, 31],
        [31, 11, 20, 46, 27],
        [27, 37, 45, 20, 38],
        [42, 10,  4, 25, 18],
        [18, 21, 27,  5, 47],
        [31, 42,  3, 28, 26],
        [16, 23, 34, 10, 19],
        [10, 27, 30, 25, 27],
        [49,  2,  7, 29, 26]],

       [[37, 16,  8, 43, 33],
        [35, 21, 44, 49, 19],
        [32,  5, 27, 26, 41],
        [ 2, 43, 46,  6, 22],
        [47, 35, 35, 25, 36],
        [ 7, 40, 24, 31, 36],
        [43, 29, 34, 44, 33],
        [39, 45, 24, 28, 29],
        [28, 42, 17, 45, 31],
        [16, 48, 34, 37,  6]],

       [[46, 44,  6, 12,  7],
        [44, 37, 48, 34, 45],
        [ 5,  5, 16, 43, 41],
        [27, 17, 13, 23, 23],
        [ 7, 20, 42, 28, 36],
        [41, 25, 26, 42, 35],
        [21, 31, 37, 14, 33],
        [49, 38, 33, 25, 11],
        [20, 36, 46,  4, 43],
        [16, 24, 27, 15, 24]],

       [[38, 48, 12, 21,  5],
        [37, 18, 38, 42, 39],
        [ 8, 43,  8, 10,  5],
    

In [58]:
arr2[:,9:,:]

array([[[49,  2,  7, 29, 26]],

       [[16, 48, 34, 37,  6]],

       [[16, 24, 27, 15, 24]],

       [[20, 41,  3, 10, 14]],

       [[35, 23, 25, 15, 41]]])

In [61]:
arr = np.array([7,5,9])
arr

array([7, 5, 9])

In [64]:
arr.argmax()


2

In [65]:
arr.argmin()

1

In [68]:
arr.sort()
arr

array([5, 7, 9])

In [69]:
arr[::-1]

array([9, 7, 5])

In [71]:
arr = np.random.randint(1,12,(10,5))
arr

array([[ 4,  6, 10,  2,  4],
       [11,  8,  4,  7,  7],
       [ 8,  2,  1, 11,  1],
       [10,  2,  4, 11,  1],
       [ 8,  4,  6,  4,  8],
       [ 4,  7,  4, 10,  5],
       [ 7, 10,  2,  4,  2],
       [ 8,  9, 10, 11, 10],
       [ 2, 11,  5,  5,  4],
       [ 1,  5,  3,  2,  4]])

In [72]:
np.unique(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [73]:
arr.var()

10.4116

In [76]:
np.median(arr)

5.0

In [78]:
arr.std()

3.2267011017446285

In [79]:
np.sqrt(25)

5.0