In [1]:
import numpy as np
print("imported")

imported


In [3]:
ls = [1,2,3,4,5,6,7]
ls

[1, 2, 3, 4, 5, 6, 7]

In [4]:
arr = np.array(ls)
arr
# it is a n dimentional array

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
type(arr)

numpy.ndarray

In [8]:
arr+5
# adds 5 in the above value 

array([ 6,  7,  8,  9, 10, 11, 12])

In [9]:
arr.dtype 
# tells the memory allcated by the element in the list i made

dtype('int64')

In [14]:
arr.ndim
# tells the number of dimention in this array ?

1

In [15]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
arr[2]
# to find the element 

np.int64(3)

In [17]:
arr[2:5:2]

array([3, 5])

In [18]:
ls

[1, 2, 3, 4, 5, 6, 7]

In [25]:
for i in ls:
    if i < 5:
     print(i)
# this will give the numbers in veritcally 



arr[arr<5]
# this will give in array itself

array([1, 2, 3, 4])

In [26]:
arr.size
# tells the leangth of the array 

7

In [27]:
len(arr)
# tells the number of element in the arr

7

In [31]:
arr2 = np.arange(100)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [35]:
np.ones((10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [39]:
np.ones((10,1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [43]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [48]:
np.linspace(1,400,5)

array([  1.  , 100.75, 200.5 , 300.25, 400.  ])

In [49]:
import random

In [53]:
random.randint(1,10)

6

In [59]:
random.random()

0.5557054812264491

In [61]:
arr = np.arange(60)
arr



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [66]:
arr2 = arr2.reshape(625)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45

In [71]:
arr2= arr2.reshape(625)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45

In [69]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45

In [73]:
arr2 =np.random.randint(2,50,(6,10,5))
arr2

array([[[20, 32, 44, 29, 20],
        [41, 28,  6, 20, 14],
        [15, 29, 26, 45,  3],
        [24, 40, 33,  5, 39],
        [34, 46, 19, 40, 29],
        [13, 37, 41, 49, 39],
        [42, 33, 18,  9, 48],
        [43,  2, 12, 37, 44],
        [11, 20, 40, 20, 21],
        [ 9, 14, 11, 11, 45]],

       [[42,  6, 13,  8, 20],
        [32, 27, 24, 44, 25],
        [27, 33, 19, 34, 43],
        [ 6,  6, 30,  8, 47],
        [14,  2, 33, 15, 47],
        [37, 18, 12, 15, 20],
        [29,  9, 24,  8,  4],
        [11,  5, 46, 22, 17],
        [37, 24, 19, 45, 48],
        [13, 33, 47, 48, 27]],

       [[35, 34, 41, 32, 21],
        [34, 41, 24,  7,  5],
        [ 4, 28, 18, 18,  3],
        [21, 38, 25, 48, 42],
        [25, 43, 24, 36, 30],
        [ 8, 35, 11, 11, 24],
        [41, 13, 47, 33, 18],
        [36,  9, 22, 15, 19],
        [24, 43, 15,  3, 49],
        [43, 36, 32, 48, 41]],

       [[28, 33, 26,  7, 40],
        [36, 18,  2, 16, 36],
        [ 8,  8, 43, 16,  4],
    